name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Derive NX_BASE and NX_HEAD manually
        shell: bash
        run: |
          echo "NX_BASE=$(echo $(git rev-parse HEAD~1))"  >> $GITHUB_ENV
          echo "NX_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - run: npm ci
      - run: npx rome ci .
      # - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --configuration=ci
      - run: npx nx affected --target=build --parallel=3
  deploy:
    needs: verify-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npx nx build cv --parallel=3 --base-href=\"/app-ideas/\"
      - uses: JamesIves/github-pages-deploy-action@releases/v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-page
          FOLDER: dist/apps/cv
