name: Deploy to GitHub Pages

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive NX_BASE and NX_HEAD manually
        shell: bash
        run: |
          echo "NX_BASE=$(echo $(git rev-parse HEAD~1))"  >> $GITHUB_ENV
          echo "NX_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - run: npm ci
      - run: npx nx affected --target=build --parallel=3
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: master
          FOLDER: dist/cv
